### PR TITLE
Add pipeline name to getpipelinevars and getpipelinesecrets AND add new module downloadbuildlogs

### PR DESCRIPTION
**Pull request by nheiniger**
This is a quality of life update. It makes variable enumeration easier. I now include the pipeline name for each variable on top of the project name. This proves very useful when you have many many pipelines in a single project and you have to search all of them for the correct variable.

There's also some refactor of the code to simplify and parse JSON results in a more convenient way.

### CODE REVIEW

**Comment by h4wkst3r** [comment]
Thanks @nheiniger! I will review this in the coming weeks.

**Comment by nheiniger** [comment]
My pleasure, note that I've added a new module too, `downloadbuildlogs`. This allows to download the pipeline logs with the idea to search for secrets inside of them (for a project or for all of them). It's not perfect, it can be super noisy, but I didn't find any other ways to search in the build logs... so I coded this one.

**Comment by h4wkst3r** [comment]
Thanks! I have been working on something similar with build logs, so I will merge our work together in the next release 👍

**Comment by h4wkst3r** [comment]
All of these updates and additions have been added to v1.3. Thank you so much @nheiniger!!!

**Pull request closed without merging**
